# Generated by Django 6.1.1 on 2026-09-29 19:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('MED', 'Medicamento'), ('INS', 'Insumo médico'), ('OTR', 'Otro')], default='MED', max_length=3)),
                ('presentacion', models.CharField(blank=True, help_text='Ej.: tableta 500 mg, jarabe 120 ml, caja de 100 unidades', max_length=80, verbose_name='presentación')),
                ('unidad_medida', models.CharField(default='unidad', max_length=30, verbose_name='unidad de medida')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='stock mínimo')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, verbose_name='número de lote')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('cantidad_actual', models.PositiveIntegerField(default=0)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.producto')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENT', 'Entrada'), ('SAL', 'Salida')], max_length=3)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.lote')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
            ],
            options={
                'ordering': ['-fecha'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='movimiento_cantidad_positiva')],
            },
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('producto', 'numero_lote'), name='lote_unico_por_producto'),
        ),
    ]
