# Generated by Django 5.2.17 on 2026-09-29 19:59

import django.db.models.deletion
import pacientes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='código ISO 3166-2')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='pacientes.departamento')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distritos', to='pacientes.municipio')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DUI', 'DUI'), ('NUI', 'NUI (Número Único de Identidad, nacidos desde 2023)'), ('CUN', 'CUN (Código Único de Nacimiento)'), ('PARTIDA', 'Partida de nacimiento'), ('MINORIDAD', 'Carné de minoridad'), ('PASAPORTE', 'Pasaporte'), ('RESIDENTE', 'Carné de residente'), ('NINGUNO', 'No presenta documento')], default='DUI', max_length=10, verbose_name='tipo de documento')),
                ('numero_documento', models.CharField(blank=True, max_length=30, verbose_name='número de documento')),
                ('documento_clave', models.CharField(blank=True, editable=False, max_length=45, null=True, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=60, verbose_name='primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=60, verbose_name='segundo apellido')),
                ('apellido_casada', models.CharField(blank=True, help_text='Solo el apellido, sin «de». Ej.: Pérez.', max_length=60, verbose_name='apellido de casada')),
                ('conocido_por', models.CharField(blank=True, max_length=100, verbose_name='conocido(a) por')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('nacionalidad', models.CharField(choices=[('SV', 'Salvadoreña'), ('EX', 'Extranjera')], default='SV', max_length=2)),
                ('pais_origen', models.CharField(blank=True, max_length=60, verbose_name='país de origen')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('ACOMPANADO', 'Acompañado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUDO', 'Viudo(a)')], max_length=10, verbose_name='estado civil')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='ocupación')),
                ('area', models.CharField(choices=[('U', 'Urbana'), ('R', 'Rural')], max_length=1, verbose_name='área')),
                ('direccion', models.CharField(help_text='Colonia, barrio, cantón o caserío; calle o pasaje; número de casa.', max_length=255, verbose_name='dirección')),
                ('punto_referencia', models.CharField(blank=True, help_text='Ej.: frente a la iglesia, a una cuadra del parque.', max_length=150, verbose_name='punto de referencia')),
                ('telefono', models.CharField(max_length=9, validators=[pacientes.validators.validar_telefono], verbose_name='teléfono')),
                ('telefono_alterno', models.CharField(blank=True, max_length=9, validators=[pacientes.validators.validar_telefono], verbose_name='teléfono alterno')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('afiliacion', models.CharField(choices=[('NINGUNA', 'Ninguna (particular)'), ('ISSS', 'ISSS'), ('ISBM', 'Bienestar Magisterial (ISBM)'), ('COSAM', 'Sanidad Militar (COSAM)'), ('PRIVADO', 'Seguro médico privado'), ('OTRA', 'Otra')], default='NINGUNA', max_length=10, verbose_name='afiliación / seguro')),
                ('numero_afiliacion', models.CharField(blank=True, max_length=30, verbose_name='número de afiliación')),
                ('nombre_madre', models.CharField(blank=True, max_length=150, verbose_name='nombre de la madre')),
                ('nombre_padre', models.CharField(blank=True, max_length=150, verbose_name='nombre del padre')),
                ('responsable_nombre', models.CharField(blank=True, max_length=150, verbose_name='nombre del responsable')),
                ('responsable_parentesco', models.CharField(blank=True, choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('CONYUGE', 'Esposo(a) / compañero(a) de vida'), ('HIJO', 'Hijo(a)'), ('HERMANO', 'Hermano(a)'), ('ABUELO', 'Abuelo(a)'), ('TIO', 'Tío(a)'), ('TUTOR', 'Tutor(a) legal'), ('OTRO', 'Otro')], max_length=10, verbose_name='parentesco')),
                ('responsable_dui', models.CharField(blank=True, max_length=10, validators=[pacientes.validators.validar_dui], verbose_name='DUI del responsable')),
                ('responsable_telefono', models.CharField(blank=True, max_length=9, validators=[pacientes.validators.validar_telefono], verbose_name='teléfono del responsable')),
                ('datos_proporcionados_por', models.CharField(blank=True, help_text='Déjelo vacío si los dio el mismo paciente. Si no, nombre y parentesco.', max_length=150, verbose_name='datos proporcionados por')),
                ('observaciones', models.TextField(blank=True)),
                ('consentimiento_datos', models.BooleanField(default=False, verbose_name='consentimiento para el tratamiento de datos personales')),
                ('fecha_consentimiento', models.DateTimeField(blank=True, editable=False, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('texto_busqueda', models.CharField(blank=True, editable=False, max_length=500)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='pacientes.distrito')),
                ('distrito_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pacientes.distrito', verbose_name='distrito de nacimiento')),
                ('registrado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'ordering': ['primer_apellido', 'segundo_apellido', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número de expediente')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='fecha de apertura')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='tipo de sangre')),
                ('alergias', models.TextField(blank=True, help_text='Medicamentos, alimentos u otras sustancias. Vacío si no refiere.')),
                ('enfermedades_cronicas', models.TextField(blank=True, help_text='Ej.: hipertensión, diabetes, asma.', verbose_name='enfermedades crónicas')),
                ('medicamentos_actuales', models.TextField(blank=True, verbose_name='medicamentos de uso continuo')),
                ('antecedentes_personales', models.TextField(blank=True, help_text='Cirugías, hospitalizaciones, enfermedades importantes.', verbose_name='antecedentes personales')),
                ('antecedentes_familiares', models.TextField(blank=True, help_text='Enfermedades de padres, hermanos o abuelos.', verbose_name='antecedentes familiares')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'historial clínico',
                'verbose_name_plural': 'historiales clínicos',
            },
        ),
        migrations.AddConstraint(
            model_name='distrito',
            constraint=models.UniqueConstraint(fields=('municipio', 'nombre'), name='distrito_unico_por_municipio'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['primer_apellido', 'nombres'], name='paciente_apellido_nombre'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['fecha_nacimiento'], name='paciente_fecha_nac'),
        ),
    ]
